/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as QualitySafetyRouteImport } from './routes/quality-safety'
import { Route as RequestAQuoteRouteImport } from './routes/request-a-quote'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as IndustriesIdRouteImport } from './routes/industries.$id'
import { Route as ManagementTeamSlugRouteImport } from './routes/management-team.$slug'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ProjectsCompletedRouteImport } from './routes/projects.completed'
import { Route as ProjectsOngoingRouteImport } from './routes/projects.ongoing'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const QualitySafetyRoute = QualitySafetyRouteImport.update({
  id: '/quality-safety',
  path: '/quality-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestAQuoteRoute = RequestAQuoteRouteImport.update({
  id: '/request-a-quote',
  path: '/request-a-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIdRoute = IndustriesIdRouteImport.update({
  id: '/industries/$id',
  path: '/industries/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementTeamSlugRoute = ManagementTeamSlugRouteImport.update({
  id: '/management-team/$slug',
  path: '/management-team/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsCompletedRoute = ProjectsCompletedRouteImport.update({
  id: '/projects/completed',
  path: '/projects/completed',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsOngoingRoute = ProjectsOngoingRouteImport.update({
  id: '/projects/ongoing',
  path: '/projects/ongoing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/equipment': typeof EquipmentRoute
  '/gallery': typeof GalleryRoute
  '/opportunities': typeof OpportunitiesRoute
  '/quality-safety': typeof QualitySafetyRoute
  '/request-a-quote': typeof RequestAQuoteRoute
  '/industries/$id': typeof IndustriesIdRoute
  '/management-team/$slug': typeof ManagementTeamSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/completed': typeof ProjectsCompletedRoute
  '/projects/ongoing': typeof ProjectsOngoingRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/industries/': typeof IndustriesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/equipment': typeof EquipmentRoute
  '/gallery': typeof GalleryRoute
  '/opportunities': typeof OpportunitiesRoute
  '/quality-safety': typeof QualitySafetyRoute
  '/request-a-quote': typeof RequestAQuoteRoute
  '/industries/$id': typeof IndustriesIdRoute
  '/management-team/$slug': typeof ManagementTeamSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/completed': typeof ProjectsCompletedRoute
  '/projects/ongoing': typeof ProjectsOngoingRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/industries': typeof IndustriesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/equipment': typeof EquipmentRoute
  '/gallery': typeof GalleryRoute
  '/opportunities': typeof OpportunitiesRoute
  '/quality-safety': typeof QualitySafetyRoute
  '/request-a-quote': typeof RequestAQuoteRoute
  '/industries/$id': typeof IndustriesIdRoute
  '/management-team/$slug': typeof ManagementTeamSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/completed': typeof ProjectsCompletedRoute
  '/projects/ongoing': typeof ProjectsOngoingRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/industries/': typeof IndustriesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/clients'
    | '/contact'
    | '/equipment'
    | '/gallery'
    | '/opportunities'
    | '/quality-safety'
    | '/request-a-quote'
    | '/industries/$id'
    | '/management-team/$slug'
    | '/projects/$slug'
    | '/projects/completed'
    | '/projects/ongoing'
    | '/services/$slug'
    | '/industries/'
    | '/projects/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/clients'
    | '/contact'
    | '/equipment'
    | '/gallery'
    | '/opportunities'
    | '/quality-safety'
    | '/request-a-quote'
    | '/industries/$id'
    | '/management-team/$slug'
    | '/projects/$slug'
    | '/projects/completed'
    | '/projects/ongoing'
    | '/services/$slug'
    | '/industries'
    | '/projects'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/clients'
    | '/contact'
    | '/equipment'
    | '/gallery'
    | '/opportunities'
    | '/quality-safety'
    | '/request-a-quote'
    | '/industries/$id'
    | '/management-team/$slug'
    | '/projects/$slug'
    | '/projects/completed'
    | '/projects/ongoing'
    | '/services/$slug'
    | '/industries/'
    | '/projects/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ClientsRoute: typeof ClientsRoute
  ContactRoute: typeof ContactRoute
  EquipmentRoute: typeof EquipmentRoute
  GalleryRoute: typeof GalleryRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  QualitySafetyRoute: typeof QualitySafetyRoute
  RequestAQuoteRoute: typeof RequestAQuoteRoute
  IndustriesIdRoute: typeof IndustriesIdRoute
  ManagementTeamSlugRoute: typeof ManagementTeamSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsCompletedRoute: typeof ProjectsCompletedRoute
  ProjectsOngoingRoute: typeof ProjectsOngoingRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality-safety': {
      id: '/quality-safety'
      path: '/quality-safety'
      fullPath: '/quality-safety'
      preLoaderRoute: typeof QualitySafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-a-quote': {
      id: '/request-a-quote'
      path: '/request-a-quote'
      fullPath: '/request-a-quote'
      preLoaderRoute: typeof RequestAQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$id': {
      id: '/industries/$id'
      path: '/industries/$id'
      fullPath: '/industries/$id'
      preLoaderRoute: typeof IndustriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-team/$slug': {
      id: '/management-team/$slug'
      path: '/management-team/$slug'
      fullPath: '/management-team/$slug'
      preLoaderRoute: typeof ManagementTeamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/completed': {
      id: '/projects/completed'
      path: '/projects/completed'
      fullPath: '/projects/completed'
      preLoaderRoute: typeof ProjectsCompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/ongoing': {
      id: '/projects/ongoing'
      path: '/projects/ongoing'
      fullPath: '/projects/ongoing'
      preLoaderRoute: typeof ProjectsOngoingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ClientsRoute: ClientsRoute,
  ContactRoute: ContactRoute,
  EquipmentRoute: EquipmentRoute,
  GalleryRoute: GalleryRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  QualitySafetyRoute: QualitySafetyRoute,
  RequestAQuoteRoute: RequestAQuoteRoute,
  IndustriesIdRoute: IndustriesIdRoute,
  ManagementTeamSlugRoute: ManagementTeamSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsCompletedRoute: ProjectsCompletedRoute,
  ProjectsOngoingRoute: ProjectsOngoingRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
